// Illustrative content for the public landing page (marketing showcase only).
// Real freelancer/gig data comes from the API everywhere else in the app —
// see MarketplaceView, which fetches live data instead of using this file.
import { Bot, Shield, MessageSquare, Award, MapPinned, BarChart2 } from "lucide-react";

export const freelancers = [
  {
    id: 1,
    name: "Priya Sharma",
    title: "Full-Stack React Developer",
    location: "Bengaluru, KA",
    rating: 4.9,
    reviews: 142,
    rate: "₹2,400/hr",
    skills: ["React", "Node.js", "MongoDB"],
    badge: "Top Rated",
    available: true,
    score: 97,
    avatar: "PS",
    color: "#7C3AED",
    img: "photo-1494790108755-2616b612b82c",
  },
  {
    id: 2,
    name: "Arjun Mehta",
    title: "UI/UX Designer & Prototyper",
    location: "Mumbai, MH",
    rating: 4.8,
    reviews: 98,
    rate: "₹1,800/hr",
    skills: ["Figma", "Framer", "Tailwind"],
    badge: "Verified",
    available: true,
    score: 94,
    avatar: "AM",
    color: "#059669",
    img: "photo-1472099645785-5658abf4ff4e",
  },
  {
    id: 3,
    name: "Meera Nair",
    title: "Mobile App Developer",
    location: "Kochi, KL",
    rating: 4.7,
    reviews: 76,
    rate: "₹2,100/hr",
    skills: ["React Native", "Flutter", "Firebase"],
    badge: "Rising Star",
    available: false,
    score: 91,
    avatar: "MN",
    color: "#06B6D4",
    img: "photo-1438761681033-6461ffad8d80",
  },
  {
    id: 4,
    name: "Rahul Gupta",
    title: "DevOps & Cloud Engineer",
    location: "Hyderabad, TS",
    rating: 4.9,
    reviews: 211,
    rate: "₹3,200/hr",
    skills: ["AWS", "Kubernetes", "Terraform"],
    badge: "Top Rated",
    available: true,
    score: 99,
    avatar: "RG",
    color: "#D97706",
    img: "photo-1507003211169-0a1dd7228f2d",
  },
  {
    id: 5,
    name: "Ananya Roy",
    title: "AI/ML Engineer",
    location: "Kolkata, WB",
    rating: 4.8,
    reviews: 63,
    rate: "₹4,000/hr",
    skills: ["Python", "TensorFlow", "NLP"],
    badge: "Verified",
    available: true,
    score: 96,
    avatar: "AR",
    color: "#DC2626",
    img: "photo-1517841905240-472988babdf9",
  },
  {
    id: 6,
    name: "Vikram Singh",
    title: "Blockchain Developer",
    location: "Pune, MH",
    rating: 4.6,
    reviews: 47,
    rate: "₹3,600/hr",
    skills: ["Solidity", "Web3.js", "Ethereum"],
    badge: "Rising Star",
    available: true,
    score: 88,
    avatar: "VS",
    color: "#1D4ED8",
    img: "photo-1500648767791-00dcc994a43e",
  },
];

export const gigs = [
  {
    id: 1,
    title: "Build React Dashboard with Analytics",
    client: "TechVentures Pvt Ltd",
    budget: "₹85,000",
    duration: "3 weeks",
    proposals: 12,
    skills: ["React", "TypeScript", "Recharts"],
    posted: "2 hours ago",
    type: "Fixed",
    location: "Bengaluru (Remote OK)",
    urgency: "high",
  },
  {
    id: 2,
    title: "Mobile App UI/UX Design — FinTech",
    client: "PayQuick Solutions",
    budget: "₹60,000",
    duration: "2 weeks",
    proposals: 7,
    skills: ["Figma", "Prototyping", "User Research"],
    posted: "5 hours ago",
    type: "Fixed",
    location: "Mumbai (Remote)",
    urgency: "medium",
  },
  {
    id: 3,
    title: "Node.js REST API Development",
    client: "LogisticsPro Inc.",
    budget: "₹1,200/hr",
    duration: "Ongoing",
    proposals: 19,
    skills: ["Node.js", "Express", "PostgreSQL"],
    posted: "1 day ago",
    type: "Hourly",
    location: "Hyderabad",
    urgency: "low",
  },
  {
    id: 4,
    title: "ML Model for Customer Churn Prediction",
    client: "GrowthMatrix",
    budget: "₹1,40,000",
    duration: "6 weeks",
    proposals: 5,
    skills: ["Python", "Scikit-learn", "Pandas"],
    posted: "3 hours ago",
    type: "Milestone",
    location: "Chennai (Remote)",
    urgency: "high",
  },
  {
    id: 5,
    title: "WordPress to Next.js Migration",
    client: "MediaHouse Digital",
    budget: "₹55,000",
    duration: "10 days",
    proposals: 23,
    skills: ["Next.js", "Headless CMS", "SEO"],
    posted: "6 hours ago",
    type: "Fixed",
    location: "Delhi NCR",
    urgency: "medium",
  },
  {
    id: 6,
    title: "AWS Infrastructure Setup & CI/CD Pipeline",
    client: "SaaS Builders Co.",
    budget: "₹95,000",
    duration: "3 weeks",
    proposals: 9,
    skills: ["AWS", "Docker", "GitHub Actions"],
    posted: "2 days ago",
    type: "Milestone",
    location: "Bengaluru (Remote OK)",
    urgency: "low",
  },
];

export const features = [
  {
    icon: Bot,
    title: "AI Job Matching",
    desc: "Skill-similarity matching algorithm ranks freelancers by skill overlap, proficiency, and reputation score.",
    color: "#7C3AED",
  },
  {
    icon: Shield,
    title: "Escrow Payments",
    desc: "Razorpay escrow holds funds securely. Milestone-based release with automatic freelancer payout.",
    color: "#059669",
  },
  {
    icon: MessageSquare,
    title: "Real-Time Chat",
    desc: "Socket.IO messaging with typing indicators and read receipts.",
    color: "#1D4ED8",
  },
  {
    icon: Award,
    title: "Reputation Scoring",
    desc: "Weighted reputation algorithm with verified reviews tied to completed gigs.",
    color: "#D97706",
  },
  {
    icon: MapPinned,
    title: "Hyperlocal Search",
    desc: "Location-based discovery with skill, price, and rating filters.",
    color: "#DC2626",
  },
  {
    icon: BarChart2,
    title: "Analytics Dashboards",
    desc: "Real-time dashboards for freelancers, clients, and admins — earnings, job success rate, and more.",
    color: "#06B6D4",
  },
];

export const categories = [
  { name: "Web Development", count: "2,341 gigs", icon: "💻", color: "#EFF6FF", border: "#BFDBFE" },
  { name: "UI/UX Design", count: "1,823 gigs", icon: "🎨", color: "#F0FDF4", border: "#BBF7D0" },
  { name: "Mobile Apps", count: "1,204 gigs", icon: "📱", color: "#FDF4FF", border: "#E9D5FF" },
  { name: "AI & Machine Learning", count: "892 gigs", icon: "🤖", color: "#FFFBEB", border: "#FDE68A" },
  { name: "DevOps & Cloud", count: "734 gigs", icon: "☁️", color: "#FFF1F2", border: "#FECDD3" },
  { name: "Content Writing", count: "1,567 gigs", icon: "✍️", color: "#F0FDFA", border: "#99F6E4" },
  { name: "Video & Animation", count: "645 gigs", icon: "🎬", color: "#FFF7ED", border: "#FED7AA" },
  { name: "Blockchain", count: "312 gigs", icon: "🔗", color: "#EEF2FF", border: "#C7D2FE" },
];
